services:
  social-app:
    build: .
    container_name: app_container
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres_db:5432/postgres
      - NEXT_PUBLIC_CLOUDINARY_API_KEY=
      - CLOUDINARY_API_SECRET=
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=
      - CLOUDINARY_URL=
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
      - CLERK_SECRET_KEY=
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
    ports:
      - '3000:3000'
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    container_name: db_container
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - socialvol:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  socialvol:
