import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/utils/Provider';
import { ClerkProvider } from '@clerk/nextjs';
import Navbar from '@/components/ui/Navbar';
import { auth } from '@clerk/nextjs/server';
import SidebarWrapper from '@/components/Sidebar/Sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ClerkProvider>
        <body className={`antialiased min-h-screen bg-black`}>
          <Navbar />
          <SidebarWrapper>{children}</SidebarWrapper>
        </body>
      </ClerkProvider>
    </html>
  );
}
